import {IconSparkles} from '@tabler/icons-react';
import {Badge, Box, Text, Group, rem} from "@mantine/core";
import  "./CreatePR.module.scss";
import {useState} from "react";

const botSummary:string = "This pull request addresses a critical bug in the user authentication " +
    "module. The issue stemmed from improper handling of user sessions, leading to unexpected logouts. The changes in this " +
    "PR include a comprehensive fix to the session management, ensuring a seamless user experience by preventing inadvertent logouts. " +
    "Additionally, the code has been optimized for better performance, and thorough testing, including unit and integration " +
    "tests, has been conducted to validate the solution. Reviewers are encouraged to focus on the modifications in the " +
    "authentication module, paying attention to code readability, maintainability, and adherence to coding standards. " +
    "This PR is a crucial step in maintaining the reliability and stability of our application.";

function PRDescription (){
  const iconSparkles = <IconSparkles style={{ width: rem(22), height: rem(22) }} />;
  const [text, setText] = useState(botSummary);
  return(
    <>
      <Group mt="md">
        <Badge leftSection={iconSparkles}  variant="gradient">
          PR Description
        </Badge>
        <Text c="dimmed">This summary is generated by bot and can be edited</Text>
      </Group>
      <Box p="md"
           style={{ position: 'relative', width: '100%', border:  'solid 0.5px cyan', borderRadius:20}}>
        <Group>
          <textarea name="description" onChange={e => {setText(e.target.value); console.log(text)}} defaultValue={text}/>
        </Group>
      </Box>
    </>
  )
}

export default PRDescription;
