name: CI

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  api-server-linter:
    name: Lint api-server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
          cache: true

      - name: dotnet format
        run: dotnet format --verify-no-changes

      - name: dotnet publish
        run: dotnet publish

  web-client-linter:
    name: Lint web-client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: web-client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run ci-check

